# Relatório de Análise VII

## Criando Agrupamentos

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('data/aluguel_residencial.csv', sep =';')
dados.head(10)

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m²,Tipo Agregado
0,0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,42.50,Apartamento
1,1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,70.00,Casa
2,2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
3,3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,16.67,Apartamento
4,4,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,26.00,Apartamento
5,5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0,29.33,Casa
6,6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0,15.38,Casa
7,7,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,21.43,Apartamento
8,8,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,16.67,Apartamento
9,9,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,50.00,Apartamento

In [3]:
del dados['Unnamed: 0']

In [4]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m²,Tipo Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,42.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,70.00,Casa
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,16.67,Apartamento
4,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,26.00,Apartamento
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0,29.33,Casa
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0,15.38,Casa
7,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,21.43,Apartamento
8,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,16.67,Apartamento
9,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,50.00,Apartamento

#### https://pandas.pydata.org/pandas-docs/stable/api.html#api-dataframe-stats

In [5]:
dados['Valor'].mean()

5046.172821405663

In [12]:
dados.Bairro

0                  Copacabana
1             Jardim Botânico
2                      Centro
3                Higienópolis
4                    Cachambi
                 ...
21821                   Méier
21822                  Centro
21823             Jacarepaguá
21824    São Francisco Xavier
21825                  Leblon
Name: Bairro, Length: 21826, dtype: object

In [21]:
bairros = dados.Bairro
selecao = dados['Bairro'].isin(bairros)
dados_bairro = bairros.drop_duplicates()

In [22]:
dados_bairro

0             Copacabana
1        Jardim Botânico
2                 Centro
3           Higienópolis
4               Cachambi
              ...
13855          Bancários
15277         Cavalcanti
15280       Rio da Prata
15412      Cidade Jardim
16428        Coelho Neto
Name: Bairro, Length: 152, dtype: object

In [23]:
grupo_bairro = dados.groupby('Bairro')

In [26]:
grupo_bairro.groups

{'Abolição': [1553, 3184, 6655, 6951, 7634, 10138, 13165, 14187, 16054, 16639, 17139, 18797, 18805, 20106, 21387], 'Alto da Boa Vista': [2201, 12039, 12556, 13240, 13438, 14518], 'Anchieta': [3017, 8880, 15660, 17811], 'Andaraí': [384, 452, 514, 613, 790, 846, 854, 996, 1191, 1416, 1421, 1685, 1912, 2014, 2683, 3137, 3216, 3489, 3578, 3738, 3856, 4227, 4572, 4773, 4876, 4883, 4961, 5545, 5753, 5990, 6232, 6450, 6529, 6911, 7168, 7408, 7889, 7890, 8064, 8430, 9190, 9290, 9334, 9380, 9713, 9929, 10104, 10255, 10275, 10859, 10940, 10947, 11079, 11516, 11818, 12292, 12762, 13243, 13385, 13389, 13769, 13897, 13931, 13938, 14214, 14592, 14668, 15915, 16009, 16504, 16509, 16599, 16654, 17510, 17769, 17794, 17913, 18212, 18433, 18754, 18888, 18918, 19041, 19668, 19750, 19770, 20100, 20219, 20516, 20866, 21028, 21074, 21114, 21326, 21455, 21543, 21582], 'Anil': [241, 572, 604, 1227, 1632, 1664, 1789, 1932, 2127, 2378, 3586, 3675, 3860, 4153, 4369, 4651, 4769, 4790, 5261, 5340, 5660, 6130, 6150, 6329, 6367, 6483, 6598, 6870, 6923, 7044, 7058, 7430, 7522, 8100, 8153, 8791, 9499, 9631, 9930, 10162, 10321, 10576, 10631, 11953, 11960, 12478, 13189, 13396, 13398, 13415, 14063, 14376, 14528, 14873, 15512, 16581, 16660, 16761, 17527, 17804, 18189, 18323, 18523, 19452, 19556, 19707, 19778, 21131, 21251, 21663, 21717], 'Arpoador': [2775, 3015, 3185, 3350, 4527, 9531, 13867, 14115, 14816, 16538, 18475, 18675], 'Bancários': [13855, 14779, 15906, 20377], 'Bangu': [1292, 1684, 1703, 2133, 3863, 3956, 4080, 7364, 10490, 10528, 10542, 11205, 11424, 11515, 11862, 13479, 14602, 17877, 18182, 20479], 'Barra da Tijuca': [5, 14, 16, 21, 30, 32, 35, 42, 43, 60, 61, 64, 68, 74, 79, 93, 107, 110, 112, 117, 130, 132, 136, 150, 153, 155, 165, 166, 173, 186, 189, 207, 214, 221, 224, 233, 236, 239, 244, 259, 265, 274, 276, 291, 292, 293, 295, 302, 308, 311, 325, 335, 336, 345, 360, 366, 368, 374, 380, 387, 389, 400, 412, 432, 433, 435, 436, 439, 449, 451, 462, 463, 465, 473, 476, 484, 494, 500, 503, 511, 537, 538, 539, 540, 543, 547, 552, 554, 555, 556, 584, 587, 588, 590, 594, 596, 601, 611, 622, 630, ...], 'Barra de Guaratiba': [3676, 10098, 19495, 20876], 'Benfica': [100, 5724, 11274, 18264, 19201], 'Bento Ribeiro': [2250, 2951, 2984, 5173, 6008, 7440, 9878, 10183, 10949, 13094, 13457, 13624, 13761, 14179, 15796, 15837, 18395, 19026, 20159, 20901, 21371, 21633, 21793], 'Bonsucesso': [67, 264, 367, 714, 918, 1288, 1459, 1512, 2064, 2219, 2668, 2678, 3058, 3233, 3258, 4130, 4259, 4353, 4925, 5140, 5451, 5630, 6731, 6866, 7584, 7733, 7977, 8607, 9784, 9888, 10037, 10430, 11447, 11863, 12338, 12356, 12371, 12905, 12923, 14931, 14942, 14959, 15378, 15983, 16148, 16464, 16610, 16889, 16960, 17022, 17420, 17786, 18086, 18890, 18970, 18994, 19652, 20593, 20926], 'Botafogo': [23, 48, 87, 88, 111, 119, 127, 134, 196, 200, 225, 334, 362, 415, 416, 498, 524, 526, 545, 593, 649, 685, 719, 756, 765, 822, 827, 861, 915, 924, 928, 1006, 1043, 1080, 1091, 1110, 1116, 1127, 1140, 1165, 1201, 1205, 1223, 1250, 1282, 1295, 1304, 1317, 1348, 1383, 1414, 1419, 1455, 1517, 1529, 1579, 1630, 1655, 1670, 1699, 1741, 1742, 1788, 1814, 1823, 1826, 1853, 1922, 1931, 1957, 1972, 1981, 1989, 2029, 2066, 2069, 2081, 2083, 2084, 2088, 2097, 2148, 2149, 2165, 2179, 2197, 2242, 2247, 2297, 2352, 2381, 2396, 2413, 2431, 2433, 2470, 2509, 2519, 2532, 2580, ...], 'Braz de Pina': [873, 3995, 4290, 5975, 6812, 6845, 7242, 9121, 9292, 12051, 12242, 12994, 14164, 15111, 15726, 15893, 17658, 18230, 19599, 19655], 'Cachambi': [4, 56, 247, 252, 525, 629, 1389, 1683, 1862, 1949, 2087, 2178, 2556, 2633, 2889, 3009, 3045, 3080, 3755, 4060, 4161, 4195, 4204, 4398, 4446, 4635, 4638, 5272, 5280, 5292, 5308, 5455, 5523, 5572, 5749, 5862, 5919, 5987, 5996, 6173, 6176, 6239, 6378, 6386, 6485, 6600, 6771, 6832, 6850, 7315, 7423, 7441, 7625, 7737, 7907, 8014, 8046, 8066, 8200, 8217, 8600, 8685, 8896, 8904, 8944, 9119, 9123, 9232, 9476, 9578, 9582, 9682, 9855, 10187, 10194, 10353, 10783, 10813, 11075, 11090, 11356, 11370, 11454, 11479, 11488, 11810, 12030, 12394, 12811, 13091, 13306, 13309, 13344, 13699, 13754, 14197, 14333, 14677, 14744, 14910, ...], 'Cachamorra': [9364], 'Cacuia': [13132, 18614, 18796], 'Caju': [2353], 'Camorim': [549, 625, 668, 1014, 1147, 1904, 1958, 1959, 2093, 2176, 3072, 4145, 5479, 5790, 5916, 6258, 6541, 6638, 8126, 8792, 9927, 9955, 10386, 11553, 12707, 12864, 13452, 13742, 13746, 14835, 14847, 15056, 15451, 16207, 17346, 18058, 18314, 18431, 18990, 19232, 19826, 20244, 20879, 20904], 'Campinho': [1120, 6526, 6939, 7401, 7482, 8596, 9413, 13130, 13245, 14461, 14546, 18131, 20422, 21309, 21802], 'Campo Grande': [22, 137, 178, 253, 322, 378, 481, 502, 531, 542, 618, 662, 677, 723, 724, 780, 909, 986, 1004, 1012, 1041, 1067, 1109, 1121, 1146, 1163, 1240, 1249, 1300, 1335, 1412, 1472, 1604, 1662, 1713, 1762, 1880, 1892, 1905, 1942, 2019, 2023, 2193, 2317, 2386, 2632, 2650, 2755, 2765, 2784, 2856, 2878, 2898, 2941, 2961, 3006, 3049, 3075, 3101, 3147, 3179, 3200, 3224, 3236, 3459, 3477, 3499, 3542, 3543, 3778, 3793, 3820, 3821, 3846, 3882, 3886, 3951, 3957, 3990, 4023, 4035, 4081, 4100, 4114, 4178, 4186, 4301, 4426, 4436, 4487, 4520, 4528, 4534, 4555, 4574, 4578, 4613, 4715, 4736, 4950, ...], 'Cascadura': [558, 879, 1625, 1925, 4452, 5816, 6283, 6614, 8551, 9319, 10272, 10844, 11782, 11842, 11998, 12250, 12723, 14902, 15569, 16030, 16035, 16075, 16737, 17067, 17580, 19602, 19606, 20057, 20095, 20268, 21751], 'Catete': [94, 98, 120, 193, 300, 339, 682, 1174, 1351, 1402, 1692, 1798, 1824, 1903, 2011, 2125, 2286, 2397, 2423, 2930, 2931, 2987, 3244, 3529, 3673, 3708, 3758, 3814, 3920, 4120, 4215, 4219, 4291, 4323, 4407, 4770, 4817, 5477, 5612, 5617, 5635, 5707, 5710, 5727, 5889, 5948, 6160, 6250, 6599, 6888, 6957, 7018, 7020, 7050, 7073, 7162, 7345, 7386, 7858, 8435, 8652, 8776, 8876, 8942, 9089, 9284, 9327, 9349, 9451, 9566, 9833, 9854, 9978, 10134, 10172, 10241, 10249, 10276, 10366, 10557, 10832, 10992, 11166, 11501, 11550, 11573, 11615, 11730, 11740, 11789, 11907, 12013, 12206, 12279, 12289, 12348, 12603, 12654, 13104, 13358, ...], 'Catumbi': [1343, 3152, 4506, 8394, 8769, 16685, 17119, 21002], 'Cavalcanti': [15277, 18152], 'Centro': [2, 38, 65, 71, 146, 181, 191, 312, 427, 585, 665, 826, 870, 939, 944, 954, 1016, 1111, 1115, 1136, 1321, 1385, 1483, 1496, 1613, 1633, 1691, 1697, 1733, 1737, 1845, 1891, 1901, 2006, 2085, 2098, 2156, 2167, 2191, 2236, 2239, 2258, 2326, 2445, 2466, 2605, 2614, 2971, 3076, 3082, 3090, 3240, 3278, 3329, 3330, 3343, 3481, 3530, 3576, 3690, 3772, 3865, 3909, 3929, 3936, 4025, 4027, 4042, 4177, 4327, 4371, 4445, 4464, 4503, 4719, 4788, 4838, 4859, 4877, 4915, 4933, 4934, 5016, 5031, 5049, 5077, 5102, 5112, 5157, 5161, 5172, 5287, 5313, 5337, 5381, 5448, 5629, 5693, 5728, 5799, ...], 'Cidade Jardim': [15412], 'Cidade Nova': [2238, 2271, 2726, 6277, 13045, 16128, 21564], 'Cocotá': [8984, 18575, 20710], 'Coelho Neto': [16428], 'Colégio': [1586, 2872, 15272, 18498], 'Copacabana': [0, 9, 10, 11, 24, 25, 28, 31, 86, 91, 104, 109, 125, 129, 140, 142, 143, 151, 162, 174, 184, 192, 194, 206, 223, 249, 263, 275, 278, 281, 289, 290, 301, 307, 319, 327, 329, 348, 359, 365, 371, 372, 388, 396, 404, 425, 426, 437, 458, 460, 485, 486, 487, 497, 530, 532, 534, 557, 564, 573, 574, 583, 606, 610, 612, 615, 633, 650, 659, 666, 667, 678, 687, 689, 694, 701, 713, 730, 736, 739, 772, 808, 824, 836, 872, 881, 894, 898, 907, 912, 917, 919, 921, 922, 929, 952, 963, 964, 980, 989, ...], 'Cordovil': [2284, 6413, 7750, 10450, 13193, 14181, 16036, 18091, 19989], 'Cosme Velho': [66, 1057, 1561, 1599, 2706, 4189, 4659, 5432, 6574, 7467, 7957, 9409, 9741, 9850, 10978, 11008, 11046, 12796, 14613, 14974, 15012, 15014, 15567, 16160, 16669, 17201, 17302, 17845, 18096, 19500, 21207], 'Cosmos': [8413, 13685, 14916, 15565, 15868, 16351, 16629, 16807, 16955, 17511, 21279, 21286], 'Curicica': [431, 619, 1184, 1208, 1489, 1693, 2075, 2203, 2244, 2582, 3337, 3597, 3753, 3954, 4096, 4757, 6269, 7228, 7700, 8040, 8249, 8325, 8703, 9041, 9819, 10001, 10128, 10314, 10591, 10788, 10918, 11189, 11236, 11543, 11544, 11876, 11949, 12083, 12507, 12551, 12642, 12653, 12695, 12935, 12980, 13467, 13625, 13760, 13987, 14299, 14838, 15279, 15392, 15495, 15965, 15984, 16109, 16588, 16634, 16638, 17219, 17604, 17854, 17996, 18127, 18637, 20269, 20363, 20688, 20715, 20790, 20808, 21108, 21331, 21502, 21747], 'Del Castilho': [2679, 2865, 3566, 3723, 3799, 4608, 6300, 6872, 8129, 8238, 8493, 8979, 9172, 11051, 11201, 11535, 13888, 14383, 15702, 16033, 18537, 19145, 20105], 'Encantado': [1087, 2001, 2446, 6242, 7531, 8083, 10236, 13209, 15334, 17133, 17270, 17791, 18156, 19301, 21695], 'Engenho Novo': [131, 231, 237, 286, 548, 1019, 1326, 1422, 1913, 1982, 2688, 2737, 2772, 2800, 2809, 2935, 3365, 3818, 4005, 4162, 4449, 5141, 5212, 5228, 5294, 5946, 6303, 6406, 6522, 6707, 7342, 7475, 7484, 7540, 7658, 7886, 7964, 8097, 8157, 8419, 8521, 8540, 8585, 8891, 9023, 9213, 9275, 9514, 9677, 9731, 9945, 10007, 10323, 10393, 10403, 10432, 11598, 11747, 11819, 11824, 11905, 12077, 12318, 12434, 12559, 13008, 13194, 13284, 13374, 13691, 13949, 13968, 14319, 14524, 14532, 15106, 15447, 15472, 15562, 16443, 16479, 16568, 16679, 16951, 17195, 17477, 17546, 17615, 17714, 18041, 18282, 18369, 18528, 18768, 19798, 19865, 20076, 20302, 20333, 20468, ...], 'Engenho da Rainha': [9293, 10017, 10367, 14637, 15380, 16523, 18031], 'Engenho de Dentro': [139, 750, 1151, 1537, 2039, 2060, 2206, 2222, 2484, 2557, 2795, 2954, 2988, 3158, 3808, 3938, 4094, 4108, 4300, 4329, 4599, 4752, 4969, 5175, 5499, 5580, 5914, 5942, 6073, 6411, 8004, 8112, 8188, 8572, 9009, 9151, 9378, 9637, 10144, 10453, 11223, 11364, 11570, 11892, 12220, 12658, 12939, 14166, 14377, 14615, 15513, 15729, 16372, 16615, 16626, 16813, 16868, 16899, 17441, 18098, 18804, 18807, 18875, 19021, 19349, 19576, 19775, 19831, 20331, 20338, 20481, 20545, 21011, 21162], 'Estácio': [2272, 2808, 3492, 4739, 5027, 5096, 5293, 5352, 5747, 7473, 8118, 13355, 14201, 14270, 15197, 15718, 15994, 17299, 17753, 18194, 18667, 20175, 21138], 'Flamengo': [78, 138, 218, 284, 321, 347, 356, 361, 369, 393, 421, 430, 442, 477, 544, 580, 620, 669, 726, 764, 795, 855, 886, 891, 900, 943, 967, 1044, 1099, 1128, 1137, 1209, 1234, 1241, 1359, 1397, 1400, 1507, 1513, 1525, 1536, 1546, 1555, 1602, 1605, 1680, 1696, 1760, 1763, 1834, 1844, 1872, 1940, 1973, 2005, 2010, 2035, 2218, 2227, 2264, 2274, 2311, 2334, 2362, 2374, 2426, 2461, 2529, 2530, 2539, 2542, 2567, 2594, 2626, 2637, 2702, 2710, 2715, 2773, 2777, 2863, 2877, 2920, 2937, 2955, 2975, 3036, 3087, 3102, 3127, 3129, 3138, 3175, 3259, 3284, 3317, 3393, 3399, 3411, 3420, ...], 'Freguesia (Ilha do Governador)': [4902, 7539, 12422, 17352, 18248], 'Freguesia (Jacarepaguá)': [13, 58, 83, 106, 123, 135, 156, 163, 188, 204, 222, 271, 305, 306, 346, 383, 455, 491, 533, 605, 688, 700, 782, 814, 863, 884, 969, 1103, 1107, 1357, 1445, 1500, 1527, 1531, 1569, 1695, 1768, 1784, 1825, 1838, 1889, 1921, 1937, 1950, 2056, 2057, 2175, 2211, 2233, 2262, 2268, 2273, 2318, 2340, 2346, 2372, 2505, 2535, 2554, 2563, 2565, 2606, 2629, 2656, 2704, 2708, 2727, 2899, 2939, 2964, 2976, 3008, 3025, 3064, 3084, 3113, 3181, 3297, 3331, 3658, 3686, 3718, 3797, 3803, 3815, 3833, 3845, 3889, 3913, 3923, 3955, 3981, 4058, 4099, 4129, 4170, 4265, 4311, 4320, 4325, ...], 'Fátima': [751, 4299, 6021, 15645, 19311, 19916], 'Gamboa': [3510, 13281, 19474], 'Gardênia Azul': [355, 2728, 5050, 6692, 8977, 11024, 12856, 17820, 21283], 'Glória': [101, 344, 403, 546, 680, 823, 960, 1005, 1676, 1833, 1876, 2012, 2095, 2112, 2159, 2344, 2395, 2415, 2739, 3726, 3744, 4140, 4541, 5333, 5345, 5447, 5740, 5744, 5784, 5911, 6152, 6770, 7062, 7090, 7099, 7485, 7560, 7597, 7624, 7631, 7952, 8361, 8402, 8949, 8966, 9287, 9815, 9975, 10053, 10056, 10234, 10246, 10415, 10492, 10696, 10777, 11144, 11241, 12317, 12385, 13041, 13303, 13318, 13440, 13453, 13561, 13589, 13633, 13806, 13996, 14198, 15342, 15434, 15665, 15887, 16383, 16571, 16696, 16848, 16851, 16921, 16933, 17192, 17398, 17605, 17792, 17883, 17914, 17958, 18175, 18378, 18620, 18986, 19394, 19429, 19844, 19858, 19888, 20092, 20217, ...], 'Grajaú': [7, 238, 317, 408, 410, 471, 570, 971, 1337, 1450, 1564, 1621, 1978, 2521, 2564, 2746, 2756, 2794, 2850, 3010, 3404, 3496, 3715, 3986, 4202, 4559, 4601, 4668, 4862, 5080, 5095, 5275, 5304, 5320, 5325, 5525, 5540, 6033, 6646, 6948, 7301, 7566, 7822, 7913, 7934, 8038, 8439, 8559, 8564, 9019, 9042, 9049, 9141, 9231, 9763, 10119, 10247, 10262, 10396, 10558, 10567, 10616, 11062, 11248, 11276, 11303, 11304, 11316, 11625, 11702, 11813, 12069, 12071, 12079, 12097, 12290, 12504, 12531, 12542, 12549, 12574, 12605, 12821, 12871, 13667, 13831, 13988, 14020, 14254, 14336, 14362, 14509, 14603, 14644, 14736, 14869, 14981, 15089, 15101, 15441, ...], 'Guadalupe': [5363, 7277, 10034, 10349, 11067, 12214], 'Guaratiba': [1239, 1320, 3903, 4358, 4410, 4450, 5605, 5876, 6085, 6566, 7655, 7674, 7837, 8130, 8796, 10167, 10322, 10459, 10800, 11565, 11597, 12207, 13804, 15360, 16157, 16181, 17096, 17313, 18078, 20746, 20755], 'Gávea': [63, 108, 215, 226, 243, 298, 461, 520, 536, 857, 1105, 1149, 1159, 1293, 1316, 1334, 1384, 1430, 1612, 1626, 1631, 2046, 2078, 2092, 2108, 2113, 2231, 2330, 2429, 2497, 2617, 2620, 2646, 2658, 2852, 2952, 2968, 3065, 3193, 3225, 3381, 3451, 3453, 3704, 3946, 4017, 4143, 4277, 4341, 4392, 4404, 4604, 4694, 4803, 4945, 4955, 4992, 5115, 5143, 5393, 5485, 5520, 5757, 5819, 5902, 5930, 6063, 6069, 6177, 6213, 6241, 6336, 6351, 6613, 6627, 6753, 6821, 7019, 7298, 7571, 7826, 7831, 8055, 8087, 8109, 8618, 8717, 8718, 8745, 8781, 8875, 8929, 9017, 9163, 9165, 9350, 9374, 9386, 9599, 9688, ...], 'Higienópolis': [3, 755, 962, 2100, 2184, 3348, 4354, 7932, 9040, 11244, 14184, 15165, 16919, 16979, 18466, 19339], 'Honório Gurgel': [9054, 9516, 13356, 16318, 18685, 18738, 21312], 'Humaitá': [36, 77, 210, 227, 288, 373, 429, 559, 830, 832, 930, 957, 1367, 1391, 1559, 1690, 1716, 1878, 1960, 2116, 2188, 2288, 2625, 3024, 3046, 3105, 3163, 3345, 3640, 3737, 3884, 3947, 4164, 4243, 4356, 4495, 4750, 4818, 4966, 5035, 5122, 5376, 5529, 5786, 6027, 6041, 6255, 6338, 7150, 7215, 7600, 7869, 7917, 7956, 8059, 8159, 8163, 8373, 8380, 8459, 8673, 8704, 8709, 8733, 8943, 9074, 9150, 9279, 9340, 9500, 9528, 9906, 10101, 10113, 10209, 10555, 10596, 10721, 11146, 11305, 11342, 11428, 11867, 12078, 12121, 12509, 12664, 12966, 13289, 13354, 13401, 13841, 14114, 14162, 14225, 14551, 14706, 14804, 14948, 14983, ...], 'Icaraí': [3146, 3601, 5000, 10891, 13397, 14242, 16459, 19110], 'Ilha do Governador': [208, 3164, 3935, 4776, 5060, 5344, 5845, 7006, 7032, 7352, 9134, 10882, 10943, 12813, 13252, 13565, 14723, 15132, 17561, 17733, 18082, 18281, 18539, 21129, 21612], 'Inhaúma': [402, 3396, 3407, 5136, 8737, 9015, 12869], 'Inhoaíba': [761, 5355, 7592, 9509, 18508, 21367], 'Ipanema': [19, 39, 40, 45, 52, 53, 73, 84, 92, 114, 121, 128, 141, 159, 177, 179, 216, 217, 230, 242, 245, 269, 283, 326, 338, 341, 370, 377, 386, 392, 405, 444, 482, 489, 515, 523, 535, 569, 575, 576, 577, 579, 589, 591, 614, 624, 628, 647, 648, 656, 671, 681, 690, 708, 710, 717, 725, 729, 731, 746, 747, 753, 757, 779, 783, 792, 800, 810, 812, 816, 829, 859, 860, 877, 888, 905, 906, 923, 927, 938, 951, 953, 970, 983, 985, 994, 1001, 1010, 1022, 1027, 1033, 1049, 1050, 1052, 1054, 1058, 1060, 1078, 1086, 1092, ...], 'Irajá': [294, 844, 1206, 1269, 1518, 2177, 2229, 2321, 2360, 2671, 3703, 4416, 4847, 4987, 6016, 6271, 6590, 6647, 6797, 6837, 7016, 7069, 7146, 7623, 7724, 7783, 7857, 8845, 9038, 9502, 9576, 9801, 9894, 10193, 10744, 10752, 11560, 11618, 11881, 11947, 12612, 12853, 12861, 13003, 13055, 13080, 13114, 13238, 13314, 13700, 13886, 14130, 14215, 14434, 14685, 14820, 14850, 15732, 16520, 17251, 17434, 17751, 18076, 18229, 18507, 18515, 18785, 18960, 19096, 19105, 19849, 19861, 20065, 21006, 21085, 21288, 21446, 21759, 21776], 'Itanhangá': [75, 474, 478, 581, 1246, 1318, 2033, 2373, 2479, 2593, 2822, 3260, 3478, 3854, 3867, 3966, 4331, 4367, 4774, 5514, 5923, 5935, 6189, 7152, 7419, 7487, 7779, 8665, 9053, 9093, 9591, 9793, 9891, 10966, 10990, 11025, 11362, 12373, 12445, 13605, 13909, 14128, 14443, 14765, 15174, 15276, 15466, 15889, 16037, 16893, 17345, 17626, 18106, 19193, 19350, 19654, 20327, 20676, 20978, 21225, 21436, 21698, 21706], 'Jabour': [817, 2117, 12692], 'Jacarepaguá': [51, 72, 198, 287, 332, 364, 505, 522, 560, 679, 709, 1046, 1219, 1468, 1567, 1615, 1643, 1806, 1990, 2153, 2232, 2269, 2332, 2465, 2511, 2555, 2575, 2623, 2628, 2676, 2796, 2820, 2862, 2868, 3311, 3375, 3402, 3452, 3571, 3631, 3700, 3702, 3775, 3801, 3859, 3931, 3997, 4045, 4085, 4196, 4256, 4264, 4302, 4455, 4570, 4634, 4699, 4798, 4853, 4973, 5073, 5079, 5094, 5200, 5241, 5257, 5277, 5407, 5435, 5484, 5497, 5604, 5725, 5739, 5812, 5842, 5871, 6028, 6051, 6151, 6501, 6547, 6772, 6807, 6928, 7042, 7095, 7134, 7139, 7163, 7287, 7347, 7393, 7464, 7850, 8203, 8227, 8233, 8239, 8285, ...], 'Jacaré': [8844, 15059, 21292], 'Jardim América': [2282, 2924, 3714, 6332, 12822, 17932, 18991], 'Jardim Botânico': [1, 55, 310, 323, 351, 445, 446, 492, 495, 571, 643, 675, 806, 937, 982, 1187, 1211, 1374, 1484, 1795, 1884, 2053, 2061, 2102, 2249, 2523, 2526, 2692, 2712, 2731, 2813, 2817, 3214, 3370, 3473, 3486, 3583, 3735, 3764, 3782, 3961, 4059, 4062, 4121, 4237, 4472, 4585, 4702, 4709, 4789, 4866, 4889, 4914, 5024, 5084, 5116, 5168, 5198, 5232, 5262, 5301, 5341, 5382, 5399, 5418, 5598, 5665, 5702, 5809, 5836, 5886, 6276, 6326, 6399, 6484, 6512, 6643, 6736, 6740, 6741, 6745, 6773, 6789, 6813, 6908, 6921, 6971, 7001, 7055, 7113, 7357, 7362, 7469, 7528, 7734, 7878, 7916, 8050, 8171, 8201, ...], 'Jardim Carioca': [95, 144, 1029, 2385, 6528, 11995, 15890, 16021, 17319], 'Jardim Guanabara': [804, 1013, 1398, 1516, 1864, 2463, 2754, 2861, 3119, 4772, 5089, 5743, 5893, 6023, 6040, 7080, 7284, 7483, 7809, 8852, 8881, 9076, 9187, 10012, 10435, 10479, 10710, 10737, 10819, 11069, 11422, 11950, 12125, 12308, 13230, 13599, 14367, 14373, 14482, 14680, 14845, 14863, 15462, 15576, 15709, 16677, 16823, 16994, 17504, 17602, 17779, 18448, 19098, 19314, 19593, 19697, 19872, 20698, 20802, 20871, 21196, 21259, 21501, 21638], 'Jardim Oceânico': [29, 203, 889, 1131, 1325, 1797, 2048, 3849, 6081, 6127, 6171, 7874, 10759, 11779, 12092, 12103, 12643, 13320, 15902, 18814, 18915, 19659, 19714], 'Jardim Sulacap': [212, 3255, 4816, 4967, 5634, 7130, 11357, 12794, 15821], 'Joá': [609, 2107, 2508, 5158, 6060, 6750, 7688, 8654, 11606, 11843, 12063, 12086, 12088, 12927, 14830, 16409, 16574, 16911, 17152, 18235, 18294, 19414, 20702], 'Lagoa': [89, 105, 124, 147, 229, 304, 318, 320, 417, 418, 428, 457, 508, 602, 626, 651, 698, 742, 760, 763, 793, 880, 942, 981, 993, 1024, 1055, 1081, 1126, 1150, 1235, 1243, 1258, 1340, 1354, 1401, 1444, 1584, 1588, 1596, 1603, 1657, 1678, 1743, 1761, 1774, 1846, 1851, 1935, 1983, 1987, 2067, 2114, 2171, 2263, 2363, 2439, 2453, 2551, 2639, 2722, 2776, 2789, 2792, 2890, 3030, 3089, 3173, 3205, 3275, 3373, 3413, 3495, 3498, 3626, 3792, 3834, 3841, 3918, 3988, 4016, 4051, 4056, 4071, 4137, 4152, 4167, 4224, 4262, 4286, 4319, 4397, 4412, 4422, 4437, 4507, 4597, 4666, 4674, 4693, ...], 'Lapa': [1296, 1805, 2310, 2966, 3197, 3336, 3727, 4279, 4834, 5362, 5818, 6391, 8457, 8931, 9196, 9351, 9803, 9876, 10830, 13921, 16694, 16958, 18200, 18682, 18882, 19671, 20319], 'Laranjeiras': [70, 154, 169, 175, 251, 272, 282, 381, 414, 467, 551, 641, 642, 645, 655, 691, 706, 720, 748, 878, 1015, 1040, 1066, 1114, 1196, 1213, 1255, 1291, 1323, 1344, 1393, 1442, 1453, 1471, 1606, 1642, 1839, 1869, 1875, 1952, 1963, 2050, 2137, 2198, 2221, 2237, 2265, 2270, 2522, 2576, 2615, 2621, 2698, 2709, 2811, 2925, 2945, 3007, 3012, 3044, 3092, 3270, 3357, 3385, 3456, 3511, 3515, 3531, 3539, 3579, 3598, 3625, 3670, 3674, 3693, 3725, 3733, 3825, 3879, 4022, 4133, 4206, 4239, 4247, 4272, 4333, 4362, 4588, 4629, 4758, 4782, 4795, 4827, 4926, 4953, 4990, 5015, 5163, 5190, 5194, ...], 'Largo do Machado': [4402, 5737, 8234, 11359, 12433], 'L

In [27]:
grupo_bairro[['Valor', 'Condominio']].mean().round(2)

                     Valor  Condominio
Bairro
Abolição           1195.33      191.40
Alto da Boa Vista  3966.67      885.00
Anchieta            875.00       19.75
Andaraí            1464.71      497.71
Anil               2048.87      455.85
...                    ...         ...
Vila Valqueire     1769.58      276.88
Vila da Penha      1260.58      232.68
Vista Alegre       1114.38      210.06
Zumbi              2150.00     1050.00
Água Santa          861.11      269.44

[152 rows x 2 columns]

In [28]:
grupo_bairro['Valor'].describe().round(2)

,count,mean,std,min,25%,50%,75%,max
Bairro,,,,,,,,
Abolição,15.0,1195.33,425.32,800.0,900.0,1180.0,1200.0,2300.0
Alto da Boa Vista,6.0,3966.67,5513.59,600.0,1150.0,1725.0,3275.0,15000.0
Anchieta,4.0,875.00,132.29,700.0,812.5,900.0,962.5,1000.0
Andaraí,97.0,1464.71,408.11,700.0,1200.0,1400.0,1650.0,2950.0
Anil,71.0,2048.87,1523.97,300.0,1100.0,1500.0,2675.0,7000.0
...,...,...,...,...,...,...,...,...
Vila Valqueire,48.0,1769.58,2203.01,800.0,1000.0,1250.0,1700.0,16000.0
Vila da Penha,104.0,1260.58,644.66,450.0,900.0,1100.0,1302.5,4500.0
Vista Alegre,16.0,1114.38,199.60,700.0,1012.5,1200.0,1225.0,1400.0
Zumbi,2.0,2150.00,777.82,1600.0,1875.0,2150.0,2425.0,2700.0
Água Santa,9.0,861.11,174.60,600.0,800.0,850.0,950.0,1200.0